name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI (${{ matrix.rust }})
    needs: ci-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.82  # Test-only, via `ntest`
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: install perf
        run: sudo apt install -y linux-tools-azure linux-cloud-tools-azure
      - name: download deps
        uses: actions/download-artifact@v4.1.8
        with:
          name: nop.exe
      - name: set up deps
        run: chmod +x nop.exe
      - name: build (debug, examples)
        run: cargo build --examples
      - name: test (debug)
        run: cargo test
      - name: "build examples (release)"
        run: cargo build --release --examples
      - name: "integration test (syscalls)"
        run: ./script/syscall-tracepoint-test ./target
      - name: "integration test (hw-breakpoints)"
        run: ./script/hw-breakpoint-test ./target ./nop.exe
  cross:
    name: Cross-compile (${{ matrix.rust }}-${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
        rust:
          - stable
          - 1.82  # Test-only, via `ntest`
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: add target ${{ matrix.rust }}-${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: check (debug)
        run: cargo check --target=${{ matrix.target }}
  ci-deps:
    name: CI dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build test-programs
        run: cd test-programs && ./build-all.sh
      - name: upload test-programs
        uses: actions/upload-artifact@v4.4.0
        with:
          name: nop.exe
          path: ./test-programs/nop/nop.exe
          retention-days: 1
