name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI (${{ matrix.rust }})
    needs: ci-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.82  # Test-only, via `ntest`
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: download test programs
        uses: actions/download-artifact@v4.1.8
        with:
          path: test-programs
          merge-multiple: true
      - name: list downloaded artifacts
        run: ls test-programs
      - name: set up test programs
        run: |
          cd test-programs
          chmod +x nop.exe
          chmod +x exec-off-leader
      - name: build (debug, examples)
        run: cargo build --examples
      - name: install nextest
        uses: taiki-e/install-action@nextest
      - name: test (release)
        run: cargo nextest run -r -P ci --color always -F test-programs
      - name: "build examples (release)"
        run: cargo build --release --examples
      # Temporarily disabled due to: https://bugs.launchpad.net/ubuntu/+source/linux-hwe-6.14/+bug/2117159
      # - name: "integration test (syscalls)"
      #   run: ./script/syscall-tracepoint-test ./target
      - name: "integration test (hw-breakpoints)"
        run: ./script/hw-breakpoint-test ./target ./test-programs/nop.exe
  cross:
    name: Cross-compile (${{ matrix.rust }}-${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
        rust:
          - stable
          - 1.82  # Test-only, via `ntest`
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: add target ${{ matrix.rust }}-${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: check (debug)
        run: cargo check --target=${{ matrix.target }}
  ci-deps:
    name: CI dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build test-programs
        run: cd test-programs && ./build-all.sh
      - name: upload test-programs (nop)
        uses: actions/upload-artifact@v4.4.0
        with:
          name: nop.exe
          path: ./test-programs/nop/nop.exe
          retention-days: 1
      - name: upload test-programs (exec-off-leader)
        uses: actions/upload-artifact@v4.4.0
        with:
          name: exec-off-leader
          path: ./test-programs/exec-off-leader/target/release/exec-off-leader
          retention-days: 1
