name: CI

on: [push, pull_request]

jobs:
  ci:
    name: ci (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.41.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: build (debug, examples)
        run: cargo build --examples
      - name: test (debug)
        run: cargo test
      - name: "build `syscalls` example (release)"
        run: cargo build --release --example syscalls
      - name: "integration test (syscalls)"
        run: ./script/syscall-tracepoint-test ./target
  cross:
    name: cross-compile (${{ matrix.rust }}-${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
        rust:
          - stable
          - 1.41.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: add target ${{ matrix.rust }}-${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: check (debug)
        run: cargo check --target=${{ matrix.target }}
